# Site settings
title: Rackspace Design System
email: design-system@rackspace.com
description: >
  Designed out of the best parts of Encore 2.0, Canon, and other Rackspace
  interfaces, Helix is an initial step toward a shared set of UX/UI components
  that designers and developers can use to deliver high quality, cohesive
  experiences for customers and Rackers alike.
baseurl: ""
cdn_url: "http://c1ee333499ed5f44e56a-fa12562cfe810d69bedcc36a0ac289ef.r55.cf1.rackcdn.com"
url: ""
twitter_username: rackspace
github_username:  rackerlabs
permalink: /:categories/:slug
# navigation: ['Style', 'Layout', 'Components', 'Templates']
exclude: ['Gemfile', 'Gemfile.lock','README.md', 'vendor', '_site', 'build-me.sh', 'Dockerfile', 'ISSUE_TEMPLATE.md', 'package.json', 'package-lock.json', 'yarn.lock']

# PATHING FOR WEBSITE AND DESIGN-SYSTEM
websiteAssets: '/assets/'

# Layouts
layouts_dir: '/templates/'
includes_dir: '/templates/_includes/'

# Build settings
markdown: HelixKramdownParser
highlighter: rouge

# Collection info
collections:
  component_code:
    output: true
    permalink: /components/code/:slug
  component_design:
    output: true
    permalink: /:categories/:slug
  docs:
    output: true
    permalink: /:categories/:slug

# SASS/SCSS
sass:
    sass_dir: assets/css/_sass
    style: compressed

# Other
# redcarpet:
#     extensions: ['tables']
kramdown:
  parse_block_html: true
#   parse_span_html: true
#   html_to_native: true

# Images Default
defaults:
  - scope:
      path: "assets/images"
    values:
      image: true
