# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Rackspace Design System
email: design-system@rackspace.com
description: > # this means to ignore newlines until "baseurl:"
  This is a UI style guide for the getcarina.com control panel v2.0. Here you will find a listing of the components available within the new 
  design system. Once specifications are created for each component we will work with our developer partners to 
  generate associated code for use and reuse across racksapce products.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://design.rax.io/design-system" # the base hostname & protocol for your site
twitter_username: rackspace
github_username:  rackerlabs
permalink: /:categories/:slug
navigation: ['Overview', 'Visual Styles', 'Components']


# PATHING FOR WEBSITE AND DESIGN-SYSTEM
websiteAssets: '/assets/website/'
designSystemAssets: '/assets/design-system/'


# Build settings
markdown: redcarpet
highlighter: rouge
gems:
- jekyll-compass